Test for #8695
This test seems to fail reliably with the current bun release. Uses
stderr rather than stdout because bun-debug currently outputs debug
information to stdout and I didn't want to filter it.

The test simply counts to 20, taking 100 ms for each write, while the
reader consumes chunks and takes one second to asynchronously process
each one.

Due to the timing-sensitive nature of the tested code, it does take 3
seconds to run, which I think is acceptable.

Output with current bun release:

490 |   let text = "";
491 |   for await (const chunk of producer.stderr) {
492 |     text += [...chunk].map(x => String.fromCharCode(x)).join("");
493 |     await new Promise(r => setTimeout(r, 1000));
494 |   }
495 |   expect(text).toBe("0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n");
        ^
error: expect(received).toBe(expected)

Expected: "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n"
Received: "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n11\n12\n13\n14\n15\n16\n17\n18\n19\n"

      at .../bun/test/js/bun/io/bun-write.test.js:495:3
(fail) timed output should work [3022.97ms]