-t should not run beforeAll/afterAll or afterEach/beforeEach for scopes that were not run
Before:

❯ bun test /Users/jarred/Code/bun/test/cli/test/test-filter-lifecycle-snapshot.test.ts
bun test v1.2.20-canary.135 (1ac2391b)

test/cli/test/test-filter-lifecycle-snapshot.test.ts:
 9 |     stderr: "pipe",
10 |     stdin: "ignore",
11 |     env: bunEnv,
12 |   });
13 |
14 |   expect(normalizeBunSnapshot(stdout.toString() + stderr.toString())).toMatchInlineSnapshot(`
                                                                           ^
error: expect(received).toMatchInlineSnapshot(expected)

Expected:
"bun test <version> (<revision>)
<parent beforeAll>
<beforeAll>
<parent beforeEach>
<beforeEach>
<test 1>
<afterEach>
<parent afterEach>
<parent beforeEach>
<beforeEach>
<test 2>
<afterEach>
<parent afterEach>
<afterAll>
<parent afterAll>

test/cli/test/test-filter-lifecycle.js:
(pass) parent > should run > test
(pass) parent > should run > test 2

 2 pass
 4 filtered out
 0 fail
Ran 2 tests across 1 file."

Received:
"bun test <version> (<revision>)
<parent beforeAll>
<beforeAll>
<afterEach>
<parent afterEach>
<parent beforeEach>
<beforeEach>
<test 1>
<afterEach>
<parent afterEach>
<parent beforeEach>
<beforeEach>
<test 2>
<afterAll>
<parent afterAll>

test/cli/test/test-filter-lifecycle.js:

# Unhandled error between tests
-------------------------------
1 | // This test is intended to be able to run in Vitest and Jest.
2 | describe("top-level sibling", () => {
3 |   beforeAll(() => {
4 |     throw new Error("FAIL");
                              ^
error: FAIL
    at <anonymous> (file:NN:NN)
      at <cwd>/test/cli/test/test-filter-lifecycle.js:2:1
    at loadAndEvaluateModule (file:NN:NN)
-------------------------------

(fail) top-level sibling > test

# Unhandled error between tests
-------------------------------
65 |     beforeEach(() => {
66 |       throw new Error("FAIL");
67 |     });
68 |
69 |     afterEach(() => {
70 |       throw new Error("FAIL");
                                 ^
error: FAIL
    at <anonymous> (file:NN:NN)
-------------------------------

(pass) parent > should run > test
(pass) parent > should run > test 2

# Unhandled error between tests
-------------------------------
106 |       console.log("<beforeEach>");
107 |     });
108 |
109 |     afterEach(() => {
110 |       if (++ran.afterEach > 2) {
111 |         throw new Error("FAIL 2");
                                      ^
error: FAIL 2
    at <anonymous> (file:NN:NN)
-------------------------------

# Unhandled error between tests
-------------------------------
106 |       console.log("<beforeEach>");
107 |     });
108 |
109 |     afterEach(() => {
110 |       if (++ran.afterEach > 2) {
111 |         throw new Error("FAIL 2");
                                      ^
error: FAIL 2
    at <anonymous> (file:NN:NN)
-------------------------------

 2 pass
 3 filtered out
 1 fail
 4 errors
Ran 3 tests across 1 file."

      at <anonymous> (/Users/jarred/Code/bun/test/cli/test/test-filter-lifecycle-snapshot.test.ts:14:71)
✗ snapshot [24.41ms]

 0 pass
 1 fail
 snapshots: 1 failed
 1 expect() calls
Ran 1 test across 1 file. [41.00ms]

After:

"bun test <version> (<revision>)
    <parent beforeAll>
    <beforeAll>
    <parent beforeEach>
    <beforeEach>
    <test 1>
    <afterEach>
    <parent afterEach>
    <parent beforeEach>
    <beforeEach>
    <test 2>
    <afterEach>
    <parent afterEach>
    <afterAll>
    <parent afterAll>

    test/cli/test/test-filter-lifecycle.js:
    (pass) parent > should run > test
    (pass) parent > should run > test 2

     2 pass
     4 filtered out
     0 fail
    Ran 2 tests across 1 file.