Add wasm-streaming.test.ts to no-validate-exceptions.txt
On my machine, I get the following failure in the "doesn't compile a
Response that isn't OK" test, and it occurs when constructing a new
Response object:

ERROR: Unchecked JS exception:
    This scope can throw a JS exception: WebCore__FetchHeaders__createFromJS @ ../../src/bun.js/bindings/bindings.cpp:1746
        (ExceptionScope::m_recursionDepth was 4)
    But the exception was unchecked as of this scope: JSGlobalObject__hasException @ ../../src/bun.js/bindings/bindings.cpp:6407
        (ExceptionScope::m_recursionDepth was 4)

I didn't touch that code, and seeing as no-validate-exceptions has a lot
of fetch-related tests, adding this test to the list seems okay.